import os

from reportlab.lib import colors
from reportlab.lib.styles import (
    getSampleStyleSheet,
    ParagraphStyle
)
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak
)

from config import Config


class PDFService:
    """
    Medical Report PDF Generator
    """

    def __init__(self):

        self.styles = getSampleStyleSheet()

        self.title_style = ParagraphStyle(
            "TitleStyle",
            parent=self.styles["Title"],
            fontSize=22,
            leading=26
        )

        self.heading_style = ParagraphStyle(
            "HeadingStyle",
            parent=self.styles["Heading2"],
            textColor=colors.HexColor("#0F5BA7")
        )

        self.body_style = ParagraphStyle(
            "BodyStyle",
            parent=self.styles["BodyText"],
            leading=18
        )

    def create_health_report(
        self,
        filename,
        report_data
    ):
        """
        Generate final healthcare PDF report.
        """

        output_path = os.path.join(
            Config.GENERATED_REPORTS_FOLDER,
            filename
        )

        document = SimpleDocTemplate(
            output_path
        )

        elements = []

        elements.append(
            Paragraph(
                Config.PDF_TITLE,
                self.title_style
            )
        )

        elements.append(
            Spacer(1, 20)
        )

        sections = [
            (
                "Patient Symptoms",
                report_data.get(
                    "symptoms",
                    "Not Available"
                )
            ),
            (
                "Symptom Analysis",
                report_data.get(
                    "analysis",
                    "Not Available"
                )
            ),
            (
                "Disease Prediction",
                report_data.get(
                    "prediction",
                    "Not Available"
                )
            ),
            (
                "Risk Assessment",
                report_data.get(
                    "risk",
                    "Not Available"
                )
            ),
            (
                "Emergency Assessment",
                report_data.get(
                    "emergency",
                    "Not Available"
                )
            ),
            (
                "Recommended Specialist",
                report_data.get(
                    "specialist",
                    "Not Available"
                )
            )
        ]

        for title, content in sections:

            elements.append(
                Paragraph(
                    title,
                    self.heading_style
                )
            )

            elements.append(
                Spacer(1, 8)
            )

            elements.append(
                Paragraph(
                    str(content).replace(
                        "\n",
                        "<br/>"
                    ),
                    self.body_style
                )
            )

            elements.append(
                Spacer(1, 15)
            )

        hospitals = report_data.get(
            "hospitals",
            []
        )

        if hospitals:

            elements.append(
                PageBreak()
            )

            elements.append(
                Paragraph(
                    "Nearby Hospitals",
                    self.heading_style
                )
            )

            elements.append(
                Spacer(1, 15)
            )

            for hospital in hospitals:

                text = f"""
                <b>{hospital.get('name')}</b><br/>
                Address: {hospital.get('address')}<br/>
                Rating: {hospital.get('rating')}
                """

                elements.append(
                    Paragraph(
                        text,
                        self.body_style
                    )
                )

                elements.append(
                    Spacer(1, 10)
                )

        elements.append(
            Spacer(1, 25)
        )

        elements.append(
            Paragraph(
                """
                DISCLAIMER:<br/>
                This report is generated by MediMind AI
                for educational and informational purposes
                only. It is not a medical diagnosis and
                should not replace consultation with a
                licensed healthcare professional.
                """,
                self.body_style
            )
        )

        document.build(elements)

        return output_path


pdf_service = PDFService()